config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user, only: [ :edit, :update, :destroy ]

  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      redirect_to pictures_path, notice: '投稿しました！'
    else
      render :new
    end
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: '投稿を更新しました！'
    else
      render :edit
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def destroy
    @picture = Picture.find(params[:id])
    if @picture.destroy
      redirect_to pictures_path, notice: '投稿を削除しました！'
    else
      render :index
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

  def authenticate_user
    unless @picture.user == current_user
      redirect_to pictures_path
    end
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :edit, :update]
  before_action :authenticate_user, only: [:show, :edit, :update ]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "ユーザー情報を更新しました！"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :image, :image_cache )
  end

  def authenticate_user
    @user = User.find(params[:id])
    unless @user == current_user
      flash[:danger] = "アクセスする権限がありません"
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= button_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>

  <div class = "field">
    <p class="mb-1 text-center"><%= form.label :image %></p>
    <%= image_tag(picture.image.url) if picture.image && picture.image.url %>

    <P class="mb-3 mt-2 text-center"><%= form.file_field :image %></P>
    <P><%= form.hidden_field :image_cache %></P>

    <P class="mb-1 text-center"><%= form.label :content %>
    <%= form.text_field :content %></P>
  <div>

    <P class="mb-1 text-center"><%= form.submit %></P>
<% end %>

app/views/pictures/confirm.html.erb
<div class ="wrapper">
  <h1>確認画面</h1>
  <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>

    <p><strong>画像:</strong></p>
    <p><%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
    <%= form.hidden_field :image_cache %>

    <p>
      <strong>コメント</strong>
      <%= form.hidden_field :content %>
      <%= @picture.content %>
    </p>

    <%= form.submit "投稿する",class:"btn btn-info mt-3 mb-3" %>
  <% end %>

  <%= form_with(model: @picture, url: new_picture_path, local: true, mothod:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit 'back', name: 'back' %>
  <% end %>
    <%= link_to '戻る', :back %>
</div>

app/views/pictures/edit.html.erb
<div class="wrapper">
  <h1>編集ページ</h1>

  <%= render "form", picture: @picture %>

  <br>
  
<p class="btn-post"><%= link_to "投稿一覧に戻る", pictures_path %></p>
</div>

app/views/pictures/index.html.erb
<div class="wrapper">
  <p style="color: green"><%= notice %></p>
  <h1>投稿一覧</h1>
  <br>
  <table>
    <table-head>
      <tr>
        <th class="pt-3 pb-3 px-5">投稿者</th>
        <th class="pt-3 pb-3 px-5">コメント</th>
        <th class="pt-3 pb-3 px-5">画像</th>
      </tr>
    </table-head>

    <table-body>
      <% @pictures.each do |picture| %>
      <tr>
        <td class="pt-3 pb-3 px-5"><%= picture.user.name %></td>
        <td class="pt-3 pb-3 px-5"><%= picture.content %></td>
        <td class="pt-3 pb-3 px-5">><%= image_tag picture.image_url(:thumb) %></td>
        <td><%= link_to '編集', edit_picture_path(picture) %></td>
        <td><%= button_to '削除', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </table-body>
  </table>

  <div class="mt-5">
    <button type="button" class="btn btn-link"><%= link_to '新規投稿ページへ', new_picture_path %></button>
  </div>

app/views/pictures/new.html.erb
<div class = "wrapper">
  <h1>新規投稿</h1>
</div>

<%= render "form", picture: @picture %>

<br>

<p class="text-center"><%= link_to "投稿一覧へ戻る", pictures_path %></p>

app/views/pictures/show.html.erb
<div class="wrapper">
  <h1>詳細ページ</h1>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>コメント:</strong>
    <%= @picture.content %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= image_tag @picture.image.url %>
  </p>

  <p><%= link_to "投稿一覧に戻る", pictures_path %></p>
  <% if @picture.user == current_user %>
  <p><%= link_to '編集する', edit_picture_path(@picture) %></p>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="wrapper">
  <h1>編集画面</h1>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user, local: true) do |f| %>
    <p class="mb-2"><%= f.label :name %></p>
    <p><%= f.text_field :name, class:"w-25" %></p>

    <p class="mb-2"><%= f.label :password %></p>
    <p><%= f.text_field :password, class:"w-25" %></p>

    <p class="mb-2"><%= f.label :password_confirmation %></p>
    <p><%= f.password_field :password_confirmation, class:"w-25" %></p>

    <%= f.submit "投稿" %>
  <% end %>
    <br>
    <%= link_to "投稿一覧画面へ戻る", pictures_path %>

app/views/users/new.html.erb
<div class="wrapper">
  <h1>Sign up</h1>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user, local: true) do |f| %>
    <p class="mb-2"><%= f.label :name %></p>
    <p><%= f.text_field :name, class:"w-25" %></p>

    <p class="mb-2"><%= f.label :password %></p>
    <p><%= f.password_field :password, class:"w-25" %></p>

    <p class="mb-2"><%= f.label :password_confirmation %></p>
    <p><%= f.password_field :password_confirmation, class:"w-25" %></p>

    <%= f.submit "Create my account" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <p style="color: green"><%= notice %></p><br><br>
  <h1>Welcome to <%= @user.name %>'s ページ</h1>

  <% if @user == current_user %>
    <p><%= link_to '編集', edit_user_path(@user), class:"btn btn-info" %></p>
  <% end %>

 <p><%= link_to '新規投稿を作成', new_picture_path, class:"btn btn-info" %></p>
</div>